{% set name = "bigearthnet-patch-interface" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f31a3ab3504ed5e72462e517aca804fce5aad2f3499fcc451ad75198e429bcc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.8,<3.11
  run:
    - natsort >=8,<9
    - numpy >=1.21,<2.0
    - pydantic >=1.9,<2.0
    - python >=3.8,<4.0

test:
  imports:
    - bigearthnet_patch_interface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kai-tub/bigearthnet_patch_interface/
  summary: A simple interface class that includes all the relevant information about BigEarthNet patches.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
